# Bozich Construction
markdown: kramdown

# URL of the Site
url: ""

# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Bozich Construction

# Description of the Site
description: We believe our clients deserve the best that the industry has to offer. The commitment we make to our clients is unmatched by our competitors.

# URL for the Image of custom Favicon
favicon-url: /favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
phone: 314-210-9336
email: operations@bozich.net
address: 11780 Manchester Drive, Saint Louis MO
instagram_username: bozich.construction
inventory: bozich.inventory

# Google Analytics
google-analytics: UA-#########-1

# SASS
sass:
  sass_dir: _sass
  style: compressed

#Plugins
plugins:
  - jekyll-tidy

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - references/
